### ISSUE TITLE
Get ICON0/PIC0/PIC1 from the ISO file during FTP fetch 

### ISSUE THREAD

**Issue by Roet-Ivar** [Roet-Ivar/Webman-Classics-Maker#16]
Get ICON0/PIC0/PIC1 from the ISO file during FTP fetch

**Comment by jimbob4000** [comment]
ICON1.PAM and SND0.AT3 would be good too, so video and sound files can play

**Comment by Roet-Ivar** [comment]
Implemented in v2.1.0
