### ISSUE TITLE
Build from long list generates same game

### ISSUE THREAD

**Issue by jimbob4000** [Roet-Ivar/Webman-Classics-Maker#19]
Builds seem to get stuck when trying to generate lots of packages, the same game gets generated.
(Tested on PS3, dev_usb000)

**Comment by jimbob4000** [comment]
Closing issue:

Reason: I manually renamed game list to include '.iso.0'. Suspect application defaulted to last known '.iso' file

**Comment by Roet-Ivar** [comment]
Thanks mate! I haven't implemented multi-storage functionality for the fetcher yet.
