### ISSUE TITLE
Feature request: Detect split iso "iso.0"

### ISSUE THREAD

**Issue by jimbob4000** [Roet-Ivar/Webman-Classics-Maker#22]
Detect "iso.0" launching seems to work

**Comment by Roet-Ivar** [comment]
Hi. Can you give me some more information about this request since I lack of knowledge regarding this. Thanks man!

**Comment by jimbob4000** [comment]
Iso files can be split so the file sizes are under 4GB for storing on external fat32 hard drives. 

The iso.0 file contains everything needed for fetching assets for the xmb bar such as icon and background images, disc code etc. 

The iso.0 file can also be launched with webman if the launch and url command string extension is changed to iso.0.

Example tool for splitting ISO’s for testing:
https://www.psx-place.com/resources/ps3-iso-tools.68/

I suspect lots of people will be using split Iso files, so think it would be a good feature. 

Thanks for the recent updates by the way, really great work.

**Comment by Roet-Ivar** [comment]
@jimbob4000 Thanks for the info buddy!
I'll add .iso0 to the scanned file-endings. As I understand webman-mod sorts out the rest regarding .iso.1 / 2 / 3 etc.

**Comment by Roet-Ivar** [comment]
@jimbob4000 you can now test this in the latest BETA-8 release in the release section.

**Comment by jimbob4000** [comment]
> @jimbob4000 you can now test this in the latest BETA-8 release in the release section.

Awesome, thanks.
Although I'm getting a FTP connection error:
```
Connection error: count() takes exactly one argument (0 given)
TIPS: Check your PS3 ip-address in webMan VSH menu (hold SELECT on the XMB)
```
Beta2 connects fine, havent tried a later one

**Comment by Roet-Ivar** [comment]
@jimbob4000 I'm sorry, it's fixed in beta-9

**Comment by jimbob4000** [comment]
> @jimbob4000 I'm sorry, it's fixed in beta-9

Thanks but I think there may be some issues.

Connection issues:
The connection seems to timeout after each game is found. 
Behaviour: Finds a game, times out, reconnects, finds another game, times out, reconnects, finds another game, times out... the cycle contninues while fetching.

I gave up waiting for the scan to finish, so not sure what the results are like and whether the iso.0 files on the external drive are scanned okay

**Comment by Roet-Ivar** [comment]
@jimbob4000 Hi! Yes I was aware of the issue just didn't have time to updated unfortunately, it's now fixed. I think you should be able to test ISO.0 extension now.

**Comment by jimbob4000** [comment]
Hi again, no joy with beta 10 unfortunately.
The USB wasn't scanned although the count looked like it knew it was there.

I'm not in any rush, so may disappear for a while, as I did a workaround a long time ago to get the same results. I think the feature would be awesome for users.

If you were curious; my workaround was a long process; I made a bash script to create my own game list and made an apple automator script to copy the image and sound assets from iso and iso.0 files. Copied the build folders to the PS3 using FTP and rebuilt the game database.

**Comment by Roet-Ivar** [comment]
Hi! Usb scanning has not been implemented yet, I suspect just changing self.xxx_path isn't enought due to other factors. 
However, since I did implement proper duplicate handling recently, needed in cases where two or more copies of the same game/title_id/filname or title (yes there are a lot of combinations here, which might need a regex replacement instead) during fetching I should now be able to implement and add fetching of the USB.

Implementation idea: 
GUI: I think I'll add a second drop down beside the platform-dropdown that allow choice of drive/path as a second platform filter.
CODE: have not yet looked into what's needed to do this but I imagine it's not too much since I hopefully made my code somewhat scalable in this regard

**Comment by Roet-Ivar** [comment]
Good news @jimbob4000 USB-scanning is now live and .ISO.0 should be working too
