### ISSUE TITLE
Support for GAMES folder

### ISSUE THREAD

**Issue by soubiliz** [Roet-Ivar/Webman-Classics-Maker#26]
PS3 game can be install both as ISO or as a folder in GAMES having both would be useful

**Comment by Roet-Ivar** [comment]
Can you brief me a little why GAMES -folder is used? Is it folder games? Thanks!

**Comment by jimbob4000** [comment]
Apologies, I think this is outside of the project goals as the game format is not an Iso. 

The GAMES folder is where multiman extracts Iso files, sometimes done for better comparability or modding.

**Comment by soubiliz** [comment]
basically webman support for ps3 both iso stored in PS3ISO and folders (extracted iso) in GAMES.
Most dumpers IRISMAN, MULTIMAN let the user choose between those two options, and extracted file take less space on the user HDD

**Comment by Roet-Ivar** [comment]
@strikersh if try the latest release you should now be able to use /GAMES and /GAMEZ respectively

**Comment by soubiliz** [comment]
I haven't used my ps3 in a while and just tested the feature it seams that you removed it in the last release
what was the issue?
