### ISSUE TITLE
PS2 and PS1 grouped content on XMB

### ISSUE THREAD

**Issue by jimbob4000** [Roet-Ivar/Webman-Classics-Maker#33]
When a built PS1 or PS2 package is installed it would be great if they were recognised by the PS3 as PS1/2 games rather than PS3. 

Not sure if it's possible. 

This categorised view on the xmb is accessed by pressing square on the gamepad. 

Thanks

**Comment by Roet-Ivar** [comment]
Hi @jimbob4000 I like this suggestion, as many others of yours! The PKGLAUNCH template that is used and modified by webMan Classics Maker is inherently seen as a PS3-title. If I remember correctly whenever its PRAMAM.SFO category is changed from PS3 to something else like PS2 it will no longer launch the game. This can be tested using the param-sfo-editor from Aldos tool-collection to see if you experience:
https://www.psx-place.com/threads/param-sfo-editor-by-aldostools.320/

**Comment by Roet-Ivar** [comment]
I had a look at this issue once again, after some research and help it's seems like a dead-end for now:
https://www.psx-place.com/threads/use-the-ps2-classics-category-keep-functionality-of-launching-eboot.31625/

**Comment by jimbob4000** [comment]
Thanks for checking 👍
