### ISSUE TITLE
RC9 file already exists bug

### ISSUE THREAD

**Issue by NextDev65** [Roet-Ivar/Webman-Classics-Maker#41]
![Screenshot 2021-01-12 114751](https://user-images.githubusercontent.com/12612637/104352416-45709600-54cc-11eb-8f51-595e9588f3f9.png)
gui wont open :[

**Comment by bajticzek** [comment]
I have the same problem. The compiled version doesn't work, even if I build it myself from source - same error.

**Comment by NextDev65** [comment]
Well I stopped trying to use this after I realized it was just making xmb shorcuts to installed stuff: just cosmetic.

**Comment by bajticzek** [comment]
Well that's what I want it for. RC7 (no binaries available) compiled just fine and works OK. So I used that instead.

**Comment by NextDev65** [comment]
> Well that's what I want it for. RC7 (no binaries available) compiled just fine and works OK. So I used that instead.

Yea RC7 was the last one that worked for me

**Comment by Naddly** [comment]
> 
> 
> > Well that's what I want it for. RC7 (no binaries available) compiled just fine and works OK. So I used that instead.
> 
> Yea RC7 was the last one that worked for me

What is RC7 and how do I use that to make my WCM work?

**Comment by NextDev65** [comment]
https://github.com/Roet-Ivar/Webman-Classics-Maker/releases/tag/webman_classics_maker_v2.2.0_RC-7
It's an older build but it worked for us.

**Comment by Naddly** [comment]
> 
> 
> https://github.com/Roet-Ivar/Webman-Classics-Maker/releases/tag/webman_classics_maker_v2.2.0_RC-7
> It's an older build but it worked for us.

Well, I'm a completely noob, so I don't know how to open that. ._. 
I suppose I have to open the .py file, but even after downloading Python it just doesn't work.
What am I doing wrong?

**Comment by Roet-Ivar** [comment]
Hi guys. I couldn't replicate this problem until I installed a fresh copy on windows. Latest release 2.2.1 should have this issue sorted.

**Comment by Roet-Ivar** [comment]
Hi guys. I couldn't replicate this problem until I installed a fresh copy on windows. Latest release 2.2.1 should have this issue sorted.
