### ISSUE TITLE
v3.0.0-beta-3 not building / saving anything

### ISSUE THREAD

**Issue by kalenderfamily** [Roet-Ivar/Webman-Classics-Maker#45]
Dear dev, really awesome tool! Since I would like to do manually I added all information selected build and save but nothing happens :-(
![manually](https://user-images.githubusercontent.com/96819979/201134205-cf9cb4b4-9875-4aae-9649-2bb945115f80.png)

**Comment by Roet-Ivar** [comment]
Could you provide a log from the window when doing this? Thank you!

**Comment by kalenderfamily** [comment]
Thanks for Response. Have been using another pkg ....

**Comment by Roet-Ivar** [comment]
Thanks! Then I'll close this issue
