### ISSUE TITLE
Feature request - making forwarders for the GAMES folder

### ISSUE THREAD

**Issue by rosewrath** [Roet-Ivar/Webman-Classics-Maker#46]
Is there any way to possibly do this, or perhaps it's in plans for the future? As of now, all of my PS3 games are in the JB folder format, instead of ISOs, located in the GAMES folder in the root of the hard drive. The PS2 games i also have work fine with webMAN Classics maker, however, any attempt to make a forwarder for a folder results in it failing, even though webMAN MOD itself does support mounting them. I'd appreciate having quick access to not just my PS2 games, but PS3 games on the XMB, without the need to convert them all to ISOs using PS3 ISO Tools. Any light on it would be appreciated!

**Comment by OctoNezd** [comment]
Its probably necroposting, but I made a PR with a fixed version of tool that works with folder games. You can try it and see if it works for you

**Comment by Roet-Ivar** [comment]
First of all I appreciate your interest in this tool, especially the pull requests! My development ceased when my CECHA console ylod, I'm planning to diagnose it and fix it soon.

Forwarders for folder GAMES used to work but got broken along the way. 

Meanwhile I need testers for these changes and depending on the results I'll make sure to merge them.

**Comment by Roet-Ivar** [comment]
PR has been approved for fixing this.

**Comment by Roet-Ivar** [comment]
PR merged, a build and proper release needs to be created.
